version: '3.1'

services:
  db:
    container_name: postgres_db
    image: postgres:13-alpine
    restart: always
    env_file: ./config/.env
    ports:
      - "5432:5432"
    volumes: 
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: