version: '3.1'

services:
  db:
    container_name: postgres_db
    image: postgres:13-alpine
    restart: always
    env_file: ./config/.env
    ports:
      - "5432:5432"
    volumes: 
      - pg_data:/var/lib/postgresql/data/

  zookeeper:
    image: 'bitnami/zookeeper:3.6'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka:
    image: 'bitnami/kafka:2.8.0'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    depends_on:
      - zookeeper

volumes:
  pg_data:
  kafka_data: